stages:
  - tests
  - integration

lint:
  stage: tests
  script: |
    pwd
    ls
    apt-get update
    apt-get install -y make git
    make -C securedrop testclean || true
    make -C securedrop images test

integration-test:
  stage: integration
  script: |
    exit 0
    cd devops/openstack
    source bootstrap
    perl -p -e 's/\$(\w+)/$ENV{$1}/e' < clouds.yml.example > clouds.yml
    cd ../..
    molecule test -s openstack
