- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
    hosts_orig: "{{ lookup('file', '../../devops/openstack/hosts-base.yml') | from_yaml }}"
  vars_files:
    - ../../devops/openstack/clouds.yml
    - ../../devops/openstack/private-key.yml
  roles:
    - { role: vm, state: absent }
#    - { role: firewall, state: absent }
