---
driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: testhost
    flavor: "s1-2"
provisioner:
  name: ansible
#  options:
#    vvv: True
  lint:
    name: ansible-lint
scenario:
  name: openstack
  test_sequence:
    - destroy
    - create
    - destroy
