---
- include_vars: clouds.yml

- name: ensure 0400 on private key
  file:
    path: '{{ ssh_private_keyfile }}'
    mode: 0400

- name: Define auth
  os_security_group: &os_auth
    auth:
      auth_url: "{{ clouds.ovh.auth.auth_url }}"
      username: "{{ clouds.ovh.auth.username }}"
      password: "{{ clouds.ovh.auth.password }}"
      project_name: "{{ clouds.ovh.auth.project_name }}"
    region_name: "{{ clouds.ovh.region_name }}"
  when: false

- name: key "{{ state }}"
  os_keypair:
    <<: *os_auth
    state: "{{ state }}"
    name: securedrop_key
    public_key_file: "{{ ssh_private_keyfile }}.pub"

- name: instances "{{ state }}"
  os_server:
    state: "{{ state }}"
    <<: *os_auth
    name: "{{ item.name }}"
    image: "{% if item.image is defined %}{{ item.image }}{% else %}Debian 9{% endif %}"
    key_name: securedrop_key
    timeout: 600
    flavor: "{{ item.flavor }}"
    auto_ip: yes
    wait: true
    userdata: |
      #cloud-config
      packages:
        - python
      package_upgrade: true
      runcmd:
        - sed -i -e '/^#Port/s/^.*$/Port {% if item.name in hosts_orig.all.hosts and hosts_orig.all.hosts[item.name].ansible_port is defined %}{{ hosts_orig.all.hosts[item.name].ansible_port }}{% else %}22{% endif %}/' /etc/ssh/sshd_config
        - systemctl restart ssh
  with_items: "{{ molecule_yml.platforms }}"
  register: server

- name: Wait for python on the instances
  command: >
    ssh -oBatchMode=yes -oStrictHostKeyChecking=no
    -p {% if item.openstack.name in hosts_orig.all.hosts and hosts_orig.all.hosts[item.openstack.name].ansible_port is defined %}{{ hosts_orig.all.hosts[item.openstack.name].ansible_port }}{% else %}22{% endif %}
    -i {{ ssh_private_keyfile }}
    {% if item.openstack.name in hosts_orig.all.hosts and hosts_orig.all.hosts[item.openstack.name].ansible_user is defined %}{{ hosts_orig.all.hosts[item.openstack.name].ansible_user }}{% else %}debian{% endif %}@{{ item.openstack.public_v4 }} which python
  register: result
  until: result|success
  retries: 30
  delay: 10
  with_items: "{{ server.results }}"
  when: state == "present"
