---
- name: Validate SASL password for OSSEC config.
  assert:
    that:
      # Ensure not the dummy value specified in example vars file.
      - sasl_password != "password123"
      - sasl_password|length >= 8
    msg: >-
      Password for OSSEC email account must be strong.
      {{ securedrop_validate_error_msg_start }} the `sasl_password` var
      is set correctly.

# Validating that vars are defined before using them to build
# service-checking commands.
- name: Ensure mail config vars are defined.
  assert:
    that:
      - smtp_relay is defined
      - sasl_domain is defined
